### ISSUE TITLE
Simplify project management?

### ISSUE THREAD

**Issue by mcandre** [abarbu/android-kawa#1]
Based on the README, something as basic as creating a new project requires executing multiple, quite involved commands. Could these.be wrapped up in a shell script, like how "rails create" works?

**Comment by abarbu** [comment]
Done. There are now 3 trivial scripts and they set up a working project for you.

**Comment by mcandre** [comment]
Thanks! You have no idea how much time and effort a little scripting saves developers downstream.

**Comment by abarbu** [comment]
No problemo. I should have made scripts to begin with. It even took me a few minutes to figure out how to create a new project.
